### ISSUE TITLE
Mistake in readme?

### ISSUE THREAD

**Issue by mbrowne** [richardanaya/webblock#2]
I think there might be a mistake in one of the code examples in the readme...

In the section "Typed Attribute Property Access", the code example contains this code:

```
attributes: {
    name: function(val){
      return val.split(":");
    }
}
```

...which is the same as the preceding example, but it doesn't seem that there's a string to split anywhere. I haven't actually tried running the example but this looked enough like a mistake that I thought I'd mention it here. Looking forward to trying out this library soon.

**Comment by richardanaya** [comment]
Thanks man, fixed
